type: "DreamBooth"

train_dataset:
  data_root: './data/dog1'
  learnable_property: "object"  # [object, style]
  size: ${resolution}
  repeats: 100
  interpolation: "bicubic"
  flip_p: 0.5
  set: "train"
  center_crop: False

train_dataloader:
  batch_size: 2
  num_workers: 4
  pin_memory: true

test_dataloader:
  batch_size: 4
  num_workers: 4
  pin_memory: true